all: ply_from_quanergy.cpp
	g++ -std=c++11 -o quanergy ply_from_quanergy.cpp -I . -I /usr/local/include -I /usr/include/pcl-1.7 -I /usr/include/eigen3 -lboost_system -lquanergy_client -lpthread -lpcl_common -lpcl_io
